language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_7adb6d095171_key -iv $encrypted_7adb6d095171_iv -in deploy_key.enc -out ./deploy_key -d
  - chmod 0400 deploy_key

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

  - echo -e "Host github.com\n  IdentityFile ${TRAVIS_BUILD_DIR}/deploy_key\n" > ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts

script:
  - mdbook build && mdbook test

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/publish.sh
  on:
    branch: master
